FROM node:stretch-slim as building

RUN mkdir /client

WORKDIR /client

ENV PATH /client/node_modules/.bin:$PATH

COPY . /client

RUN apt-get update
RUN npm install
RUN npm audit fix
RUN npm run build

FROM nginx:latest

RUN mkdir /client

WORKDIR /client

COPY --from=building /client/build /client/build

COPY ./nginx.conf /etc/nginx/nginx.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
