FROM node:stretch-slim as staging

RUN mkdir /client

WORKDIR /client

ENV PATH /client/node_modules/.bin:$PATH

COPY . /client

RUN apt-get update
RUN npm install
RUN npm build


FROM nginx

COPY --from=staging /client/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
