FROM node:stretch-slim as building
RUN mkdir /client

WORKDIR /client

ENV PATH /client/node_modules/.bin:$PATH

COPY . /client

RUN apt-get update
RUN npm install
RUN npm run build


FROM nginx:latest

COPY --from=building /client/build /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
