---
name: client-CI/CD

on:
  push:
    tags:
      - 'v*'
    branches: 
    - deployment-client 
    - development-client 
    - master-client
  pull_request:
    tags:
      - 'v*'
    branches:
    - development-client 
    - master-client

jobs:
  pipeline:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04]
    name: pipeline
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Build, cache and push docker image
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: mayankshar21
        password: "${{ secrets.GITHUB_TOKEN }}"
        registry: docker.pkg.github.com
        image_name: paediatrics-ssq-client
        image_tag: latest
        dockerfile: Dockerfile
        push_git_tag: true
    - name: Test
      run: echo testing ....
    - name: Deploy 
      run: echo deploying ....
    - name: Release
      run: echo releasing ....
    - name: Publish
      run: echo publishing ....



