---
name: client-CI/CD

on:
  push:
    branches: 
    - deployment-client 
    - development-client 
    - master-client
    tags:
      - v*
  pull_request:
    branches:
    - development-client 
    - master-client
    tags:
      - v*

jobs:
  pipeline:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04]
    name: pipeline
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build, cache and push docker image
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: mayankshar21
        password: "${{ secrets.GITHUB_TOKEN }}"
        registry: docker.pkg.github.com
        image_name: paediatrics-ssq-client
        image_tag: latest
        dockerfile: Dockerfile
        push_git_tag: true
    - name: Test
      run: echo testing ....
    - name: Deploy react app to EC2 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_NAME }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.SERVER_KEY }}
        script: whoami




