#!/bin/bash
# ####################################################################
# PIPELINE YAML FILE
# ####################################################################
# Mayank Sharma - 22th August 2020
#
# This YAML file runs a pipeline in GitHub Actions containing a number of jobs.
# Jobs include testing the code, building the image, caching the image, publishing
# the image to GitHub registry, transfering the files to the production server and 
# deploying the backend on the server.

---
name: server-CI/CD

on:
  # Pipeline trigger on push
  push:
    branches: 
    - deployment-server 
    - development-server
  # Pipeline trigger on pull request
  pull_request:
    branches:
    - development-server

jobs:
  # Testing server code with mocha
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
    # Checking out code to server
    - name: Checkout
      uses: actions/checkout@v2
    # Setting up Node.js 14.8 for testing    
    - name: Set up Node.js 14.x for testing
      uses: actions/setup-node@v1
      with:
        node-version: 14.8
    # Installing npm dependencies  
    - name: Install dependencies    
      run: npm install
    # Running ESlint
    - name: Lint with ESlint 
      uses: getsentry/action-eslint-fix@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        dry: true

  # Deploy nodejs to heroku
  deploy:
    needs: test
    runs-on: ubuntu-latest
    name: deploy
    steps:
    # Checking out code to server
    - name: Checkout
      uses: actions/checkout@v2
    # Setting up heroku
    - name: Set up Heroku
      uses: akhileshns/heroku-deploy@v3.5.6
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}} # Heroku key
        heroku_app_name: "dev-server" # Heroku app name
        heroku_email: ${{secrets.HEROKU_EMAIL}} # Heroku email
      env:
        HD_SERVER: ${{secrets.HEROKU_SERVER}} # Server URL
        HD_CLIENT: ${{secrets.HEROKU_CLIENT}} # Client URL
