# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ deployment-client ]
  pull_request:
    branches: [ deployment-client ]

jobs:
  ci-cd:
    
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        os: [ ubuntu-latest, macOS-latest ]

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run CI
      run: npm ci
    - name: Test react app
      run: echo "Will add python tests"
    - name: Build npm
      run: npm run build