# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ deployment-client ]
  pull_request:
    branches: [ deployment-client ]

jobs:
  ci-cd:
    
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        os: [ ubuntu-latest, macOS-latest ]

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        # registry-url: https://npm.pkg.github.com/
    - name: Run CI
      run: npm ci
    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          ~/cache
          !~/cache/exclude
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Test react app
      run: echo "Will add python tests"
    - name: Install static server
      run: npm install -g serve
    - name: Build react app:ci
      run: npm run build
      env: 
        CI: ""
    # - name: Publish react package to registry
    #   run: npm publish
    #   env:
    #     NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
