#!/bin/bash
# ####################################################################
# PIPELINE YAML FILE
# ####################################################################
# Mayank Sharma - 22th August 2020
#
# This YAML file runs a pipeline in GitHub Actions containing a number of jobs.
# Jobs include testing the code and deploying the deployment-client and development-client branches
# to Heroku.

---
name: client-CI/CD

on:
  # Pipeline trigger on push
  push:
    branches: 
    - production-client
  # Pipeline trigger on pull request    
  pull_request:
    branches:
    - production-client

jobs:
  # Linting client code with flake8
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
    # Checking out code to server
    - name: Checkout
      uses: actions/checkout@v2 
    # Setting up Python 3.8 for linting   
    - name: Set up Python 3.8 for Linting
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    # Installing pip dependencies
    - name: Install dependencies
      run: |
        cd src/testing/Sprint1
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # Running flake8
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        cd ../../

  # Deploy reactjs to heroku
  deploy:
    needs: test
    runs-on: ubuntu-latest
    name: deploy
    steps:
    # Checking out code to server
    - name: Checkout
      uses: actions/checkout@v2
    # Setting up heroku
    - name: Set up Heroku
      uses: akhileshns/heroku-deploy@v3.5.6
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}} # Heroku key
        heroku_app_name: "ssq-client" # Heroku app name
        heroku_email: ${{secrets.HEROKU_EMAIL}} # Heroku email
        buildpack: "https://github.com/mars/create-react-app-buildpack.git" # Buildpack
      env:
        HD_REACT_APP_SERVER: ${{secrets.HEROKU_SERVER}} # Server URL
        HD_REACT_APP_CLIENT: ${{secrets.HEROKU_CLIENT}} # Client URL

  



