# ####################################################################
# PIPELINE YAML FILE
# ####################################################################
# Mayank Sharma - 22th August 2020
#
# This YAML file runs a pipeline in GitHub Actions.
# Jobs include deploying the production-server branch to Heroku.

---
name: server-CI/CD

on:
  # Pipeline trigger on push
  push:
    branches:
    - production-server
  # Pipeline trigger on pull request
  pull_request:
    branches:
    - production-server

jobs:
  # Deploy nodejs to heroku
  deploy:
    runs-on: ubuntu-latest
    name: deploy
    steps:
    # Checking out code to server
    - name: Checkout
      uses: actions/checkout@v2
    # Setting up heroku
    - name: Set up Heroku
      uses: akhileshns/heroku-deploy@v3.5.6
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}} # Heroku key
        heroku_app_name: "ssq-server" # Heroku app name
        heroku_email: ${{secrets.HEROKU_EMAIL}} # Heroku email
      env:
        HD_SERVER: ${{secrets.HEROKU_SERVER}} # Server URL
        HD_CLIENT: ${{secrets.HEROKU_CLIENT}} # Client URL
        HD_GMAILUSERNAME: ${{secrets.HEROKU_GMAILUSERNAME}} # Gmail username
        HD_GMAILPASSWORD: ${{secrets.HEROKU_GMAILPASSWORD}} # Gmail password
        HD_MONGOURI: ${{secrets.HEROKU_MONGOURI}} # Mongo URI

        