# ####################################################################
# PIPELINE YAML FILE
# ####################################################################
# Mayank Sharma - 22th August 2020
#
# This YAML file runs a pipeline in GitHub Actions containing a number of jobs.
# Jobs include linting the code and deploying the production-server branch to Heroku.

---
name: server-CI/CD

on:
  # Pipeline trigger on push
  push:
    branches:
    - deployment-server-update 
    - production-server
  # Pipeline trigger on pull request
  pull_request:
    branches:
    - production-server

jobs:
  # Linting server code with eslint
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
    # Checking out code to server
    - name: Checkout
      uses: actions/checkout@v2
    # Setting up Node.js 14.8 for linting    
    - name: Set up Node.js 14.x for Linting
      uses: actions/setup-node@v1
      with:
        node-version: 14.8
    # Installing npm dependencies  
    - name: Install dependencies    
      run: |
        npm install
        npm install eslint --save-dev
        eslint --init
    # Running eslint
    - name: Run linters
      uses: wearerequired/lint-action@v1
      with:
        github_token: ${{ secrets.github_token }}
        eslint: true

  # Deploy nodejs to heroku
  #deploy:
  #  needs: test
  #  runs-on: ubuntu-latest
  #  name: deploy
  #  steps:
  #  # Checking out code to server
  #  - name: Checkout
  #    uses: actions/checkout@v2
  #  # Setting up heroku
  #  - name: Set up Heroku
  #    uses: akhileshns/heroku-deploy@v3.5.6
  #    with:
  #      heroku_api_key: ${{secrets.HEROKU_API_KEY}} # Heroku key
  #      heroku_app_name: "ssq-server" # Heroku app name
  #      heroku_email: ${{secrets.HEROKU_EMAIL}} # Heroku email
  #    env:
  #      HD_SERVER: ${{secrets.HEROKU_SERVER}} # Server URL
  #      HD_CLIENT: ${{secrets.HEROKU_CLIENT}} # Client URL
  #      HD_GMAILUSERNAME: ${{secrets.HEROKU_GMAILUSERNAME}} # Gmail username
  #      HD_GMAILPASSWORD: ${{secrets.HEROKU_GMAILPASSWORD}} # Gmail password
  #      HD_MONGOURI: ${{secrets.HEROKU_MONGOURI}} # Mongo URI

        