#!/bin/bash
# ####################################################################
# PIPELINE YAML FILE
# ####################################################################
# Mayank Sharma - 22th August 2020
#
# This YAML file runs a pipeline in GitHub Actions containing a number of jobs.
# Jobs include testing the code, building the image, caching the image, publishing
# the image to GitHub registry, transfering the files to the production server and 
# deploying the backend on the server.

---
name: server-CI/CD

on:
  # Pipeline trigger on push
  push:
    branches: 
    - deployment-server 
    - development-server
    - master-server 
  # Pipeline trigger on pull request
  pull_request:
    branches:
    - development-server
    - master-server

jobs:
  # Test server code with mocha
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    name: test
    steps:
    - name: Checkout
      uses: actions/checkout@v2    
    - name: Set up Node.js 14.x for testing
      uses: actions/setup-node@v1
      with:
        node-version: 14.8
    - name: Install dependencies    
      run: npm install
    #- name: Run mocha tests
    #  run: npm test

  # Deploy nodejs to heroku
  deploy:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]
    name: deploy
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Heroku
      uses: akhileshns/heroku-deploy@v3.5.6
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "dev-server"
        heroku_email: ${{secrets.HEROKU_EMAIL}}
      env:
        HD_SERVER: ${{secrets.HEROKU_SERVER}}
        HD_CLIENT: ${{secrets.HEROKU_CLIENT}}
