---
name: server-CI/CD

on:
  push:
    branches: 
    - deployment-server 
    - development-server 
    - master-server
  pull_request:
    branches:
    - development-server 
    - master-server

jobs:
  pipeline:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04, macos-latest, windows-latest]
    name: pipeline
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Build
      run: echo building ....
    - name: Cache
      run: Caching build ....
    - name: Test
      run: echo testing ....
    - name: Deploy 
      run: echo deploying ....
    - name: Release
      run: echo releasing ....
    - name: Publish
      run: echo publishing ....



