#!/bin/bash
# ####################################################################
# PIPELINE YAML FILE
# ####################################################################
# Mayank Sharma - 22th August 2020
#
# This YAML file runs a pipeline in GitHub Actions containing a number of jobs.
# Jobs include testing the code, building the image, caching the image, publishing
# the image to GitHub registry, transfering the files to the production server and 
# deploying the backend on the server.

---
name: server-CI/CD

on:
  # Pipeline trigger on push
  push:
    branches: 
    - deployment-server 
    - development-server 
    tags:
      - v*
  # Pipeline trigger on pull request
  pull_request:
    branches:
    - development-server
    tags:
      - v*

jobs:
  # Test server code with mocha
  npm_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    name: npm test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up Node.js 14.x for testing
      uses: actions/setup-node@v1
      with:
        node-version: 14.8

    - name: Install dependencies    
      run: npm ci

  # Build nodejs and deploy to heroku
  Npm_build_deploy:
    needs: npm_test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]
    name: Npm_build_deploy
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Heroku
      uses: akhileshns/heroku-deploy@v3.5.6
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "dev-server" #Must be unique in Heroku
        heroku_email: ${{secrets.HEROKU_EMAIL}}
      env:
        HD_SERVER: ${{secrets.HEROKU_SERVER}}
        HD_CLIENT: ${{secrets.HEROKU_CLIENT}}
