---
name: server-CI/CD

on:
  push:
    branches: [development-server]

jobs:  
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: testing if it works
      run: echo building ....




